### ISSUE TITLE
Missing text for actions

### ISSUE THREAD

**Issue by Info-BC** [ONLYOFFICE/onlyoffice-sharepoint#11]
Hello, after installation, it works but I have some missing texts for the actions :

On the Onlyoffice/Settings.aspx page, in front of the server url input field, I have "$Resources:Resource,DocumentServer;"
and the button bellow have "$Resources:Resource,Save;"

Same on a document menu, the edit function
![image](https://user-images.githubusercontent.com/92523501/137312774-9deb55e7-9a5f-49fd-9c3c-a5d22def9d12.png)

And also on the top of the library
![image](https://user-images.githubusercontent.com/92523501/137312981-28e119f2-e13d-4e7e-963d-808c12f4695d.png)

I guess all the texts from the application are missing
Modern or classic experience, it's the same.

Could-you help me to fix this?
Thanks

**Comment by Antipkin-A** [comment]
@Info-BC, Hi
What versions of onlyoffice connector and sharepoint do you use?

**Comment by Info-BC** [comment]
Here is my solution to add a translation file : rename .wsp to .cab, extract to a directory, add Resource.xx-XX.resx with your translation in Resources directory, modify manifest.xml to add your rootfile location, use [WSP Repackage](https://bindtuning.com/resources/blog/how-to-manually-edit-a-sharepoint-wsp-file) to generate your modified wsp file.
