### ISSUE TITLE
Error impossible to access file - Sharepoint Foundation 2013

### ISSUE THREAD

**Issue by RomainDev25** [ONLYOFFICE/onlyoffice-sharepoint#4]
Hello, we install a fresh Sharepoint Foundation 2013 and we want to implement OnlyOffice docs.

We install it on docker and we make installation on Sharepoint Install.ps1 has an error with Enable-SPFeature, so we do with command in powershell.

And after we enable it in Sharepoint Administration Center.

![Capture d’écran 2020-11-19 à 07 53 42](https://user-images.githubusercontent.com/24386544/99631754-6a9cd700-2a3c-11eb-8f22-652b22039c02.png)

But after enable it, we don't have OnlyOffice Settings like in this video : 
https://www.youtube.com/watch?v=5rN7CksWE-w

Can you help us ?

Have a nice day.

**Comment by ShockwaveNN** [comment]
@DenisDeeSign Please, take a look

**Comment by RomainDev25** [comment]
Ok I find problem, version 1.1 is not compatible with Sharepoint Foundation 2013.

But I have a problem with solution.
I have docker Onlyoffice DocsServer with SSL, it's ok with wildcard ssl.
But I have an error to open document.

![Capture d’écran 2020-11-19 à 15 36 40](https://user-images.githubusercontent.com/24386544/99680201-149c5380-2a7d-11eb-8789-843e363abc38.png)

![Capture d’écran 2020-11-19 à 15 36 31](https://user-images.githubusercontent.com/24386544/99680224-1a923480-2a7d-11eb-9872-955a56e7dde7.png)

Can you help me ?

**Comment by igwyd** [comment]
Hello @RomainDev25, sorry for the late reply. Try to add
 
`<sharepointip>  <sharepointsitename>`

to your file /etc/hosts into docker container and then restart services

`supervisorctl restart all`
