### ISSUE TITLE
Error "Download Failed" when open files in folder with name in russian

### ISSUE THREAD

**Issue by igwyd** [ONLYOFFICE/onlyoffice-sharepoint#5]
SharePoint 2016 on Windows server 2016  
onlyoffice/documentserver-ee:6.1.0.83 in docker on other linux server 

1. Create a folder in the sharepoint library with the name "Документы для тестирования длинно"
2. load any document (docx, pptx, xlsx) in folder 
3. try open document  
4. [error](https://user-images.githubusercontent.com/67538082/102778654-06a36080-43a4-11eb-8f9a-03a835f4e6d2.jpg)

ONLYOFFICE Docs log /var/log/onlyoffice/documentserver/docservice/[out.log](https://github.com/igwyd/Other/blob/main/out.log)

 SharePoint log C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\LOGS [EC2AMAZ-UDBGRNI-20201221-1514.log
](https://user-images.githubusercontent.com/67538082/102780471-09ec1b80-43a7-11eb-8169-88b6b18296be.jpg)

PS if create a folder in the sharepoint library with the name "Документы для тестирования длинне" -> load any document (docx, pptx, xlsx) here -> open documet, no errors

**Comment by DenisDeeSign** [comment]
@LinneyS, please take a look.
